version: '3'

services:
  nlrk-circulation-api:
    container_name: nlrk-circulation-api
    image: shaisarov/nlrk-circulation-api
    restart: unless-stopped
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "8590:8590"
    environment:
      - LISTEN=:8590
      - DEBUG=1
      - DATASTORE=postgres
      - DATASTORE_URL=postgres://postgres:postgres@192.168.7.241:5432/nlrk
      - DATASTORE_DB=nlrk
      - ORDER_GRPC_ADDRESS=nlrk-order:8909
      - READER_GRPC_ADDRESS=nlrk-reader:8906
      - SSO_GRPC_ADDRESS=nlrk-sso:8908
      - EBOOK_GRPC_ADDRESS=nlrk-ebook:8911
      - JWT_KEY=QowdicuD2K6h7oVpI4z7GjeX5COGRY52
    networks:
      - web_rabis_network
networks:
  web_rabis_network:
    external: true