version: '3'

services:
  nlrk-circulation-service:
    container_name: nlrk-circulation-service
    image: shaisarov/nlrk-circulation-service
    restart: unless-stopped
    build:
      context: .
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    ports:
      - "8588:8588"
    environment:
      - LISTEN=:8585
      - DEBUG=1
      - DATASTORE=postgres
      - DATASTORE_URL=postgres://postgres:postgres@192.168.7.241:5432/nlrk
      - DATASTORE_DB=nlrk
    networks:
      - web_rabis_network
networks:
  web_rabis_network:
    external: true